### ISSUE TITLE
Misaligned exception messages

### ISSUE THREAD

**Issue by dbeatty10** [yu-iskw/dbt-unittest#4]
## Overview
A few exception messages appear misaligned:
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_in.sql
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_false.sql
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_is_not_none.sql
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_not_equals.sql
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_list_equals.sql
* https://github.com/yu-iskw/dbt-unittest/blob/0.1.1/macros/assert_dict_equals.sql

## Are you willing to contribute the resolution?
Yep, submitting it shortly 😎

**Comment by yu-iskw** [comment]
The patch has been released at `v0.2.0`. Thank you!

https://github.com/yu-iskw/dbt-unittest/releases/tag/v0.2.0

**Comment by dbeatty10** [comment]
🎉 
You are welcome. Thanks for publishing the handy macros in this package.
