### ISSUE TITLE
assert_not_in is not implemented

### ISSUE THREAD

**Issue by ernestoongaro** [yu-iskw/dbt-unittest#7]
assert_not_in is not implemented, but is documented

**Comment by yu-iskw** [comment]
@ernestoongaro I have merged the pull request. Let me close it. Thanks!

**Comment by yu-iskw** [comment]
I have published the new version as `0.3.0`. I have decided notto prepend the v prefix to a version as v0.2.0 from this version so that we follow the manner as other dbt Packages do. Sorry for the inconsistent versioning.
https://github.com/yu-iskw/dbt-unittest/releases/tag/0.3.0

**Comment by ernestoongaro** [comment]
Amazing. Thank you so much for merging and releasing so quickly! Using it
for a package and it’s really helpful
